// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntiribdqwmuirszfadvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50aXJpYmRxd211aXJzemZhZHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NDEyNTAsImV4cCI6MjA3OTExNzI1MH0.LHS5fs5GYhCP-aHEoTLZf9Mv-2g_Q-35NR21asCjFTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});